### ISSUE TITLE
useReorderableDragEnd callback is never called

### ISSUE THREAD

**Issue by zarv1k** [omahili/react-native-reorderable-list#13] opened 2024-12-04 14:51 UTC
The callback passed into `useReorderableDragEnd(callback)` is never called if I use exported `useReorderableDragEnd` hook in client's code.

It happens when I use wrapper `ReorderableListItem` that already uses the `useReorderableDragEnd` hook for scale and opacity decorations implementation.

It seems the root of the issue that in implementation of `useReorderableDragEnd` there is a mutation `releasedIndex.value = -1;` that prevents callback to be called in next usage `useReorderableDragEnd(callback)` in client's code.

**Comment by omahili** [comment] 2024-12-08 16:58
Hi @zarv1k, I was able to reproduce this behavior and it's indeed due to the index being reset. However it's necessary in order for the hook not to be triggered again after re-render on reorder. I'll try and see if there's a way around it.

**Comment by zarv1k** [comment] 2024-12-08 20:13
> Hi @zarv1k, I was able to reproduce this behavior and it's indeed due to the index being reset. However it's necessary in order for the hook not to be triggered again after re-render on reorder. I'll try and see if there's a way around it.

Thank you!
I see the commit
https://github.com/omahili/react-native-reorderable-list/commit/bffbe0b6d5137a63f50a89cf7c6bd36b045b4278. Looks like the issue is already fixed, is not it?
Could you please publish the new release version with the fix?

**Comment by omahili** [comment] 2024-12-08 20:36
You're welcome! I tried, but npm is currently under [maintainance](https://status.npmjs.org/). Will do as soon as it's available again.

**Comment by omahili** [comment] 2024-12-09 08:28
Fixed in 0.5.1.

**Closed by omahili** 2024-12-09 08:28 UTC
